<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove($(MSBuildThisFile), $(MSBuildThisFileDirectory)..))" />

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <PublishNativeAOTTests>true</PublishNativeAOTTests>
    <IsPackable>false</IsPackable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <UseAppHost Condition="'$(RuntimeIdentifier)' == '' and '$(NativeAOT)' != 'true'">false</UseAppHost>
  </PropertyGroup>

  <PropertyGroup Condition="'$(NativeAOT)' == 'true' and '$(PublishNativeAOTTests)' == 'true'">
    <RuntimeIdentifier>$(DefaultRuntimeIdentifier)</RuntimeIdentifier>
  </PropertyGroup>

</Project>
