<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsTestProject>false</IsTestProject>
    <RuntimeIdentifier>$(DefaultRuntimeIdentifier)</RuntimeIdentifier>
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>

  <Import Project="..\AOT.props" />

  <ItemGroup>
    <TrimmerRootAssembly Include="Library" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Library\Library.csproj" />
  </ItemGroup>
</Project>
