<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <TargetFrameworks Condition="'$(OS)' == 'Windows_NT'">$(TargetFrameworks);net472</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Library\Library.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="TUnit.Engine" />
    <PackageReference Include="xunit.v3.assert.aot" Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)','net9.0'))" />
    <PackageReference Include="xunit.v3.assert" Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)','net9.0'))" />
  </ItemGroup>

</Project>
