steps:
- download: current
  artifact: coverageResults-Windows
  displayName: 🔻 Download Windows code coverage results
  continueOnError: true
- download: current
  artifact: coverageResults-Linux
  displayName: 🔻 Download Linux code coverage results
  continueOnError: true
- powershell: azure-pipelines/Merge-CodeCoverage.ps1 -Path '$(Pipeline.Workspace)' -OutputDir coveragereport -Format Cobertura -Verbose
  displayName: ⚙ Merge coverage
- task: PublishCodeCoverageResults@1
  displayName: 📢 Publish code coverage results to Azure DevOps
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation: coveragereport/Cobertura.xml
    failIfCoverageEmpty: true
